# Generated by Django 4.0.4 on 2022-05-05 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_reason',
            field=models.CharField(choices=[('GC', 'General Consultation'), ('DC', 'Dental cleaning'), ('CR', 'Crowns'), ('BR', 'Braces'), ('TW', 'Teeth whitening')], default='CG', max_length=2),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='id_card',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_card',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='id_card',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
